import {
  LayoutDashboard,
  Server,
  Disc,
  BarChart3,
  Upload,
  Search,
  Settings,
  Users,
  Database,
  Sliders,
  Layers,
  Warehouse,
  MapPin,
  Network,
  FileText,
  Laptop,
  HardDrive,
  Printer,
  Zap,
  Smartphone,
  Folder,
  Globe,
  ShieldCheck,
  ListTree,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  server: Server,
  disc: Disc,
  "bar-chart-3": BarChart3,
  upload: Upload,
  search: Search,
  settings: Settings,
  users: Users,
  database: Database,
  sliders: Sliders,
  layers: Layers,
  warehouse: Warehouse,
  "map-pin": MapPin,
  network: Network,
  "file-text": FileText,
  laptop: Laptop,
  "hard-drive": HardDrive,
  printer: Printer,
  zap: Zap,
  smartphone: Smartphone,
  folder: Folder,
  globe: Globe,
  "shield-check": ShieldCheck,
  "list-tree": ListTree,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? LayoutDashboard;
  return <Icon className={className} />;
}
