export interface NetworkDeviceListItem {
  assetId: number;
  assetTag: string;
  name: string;
  assetTypeName: string | null;
  manufacturerName: string | null;
  model: string | null;
  serialNumber: string | null;
  statusCode: string;
  statusName: string;
  statusColorToken: string;
  macAddress: string | null;
  managementIpAddress: string | null;
  stackInfo: string | null;
  locationName: string | null;
  eolDate: string | null;
}

export interface NetworkDeviceDetail {
  assetId: number;
  assetTag: string;
  name: string;
  categoryId: number;
  categoryName: string;
  assetTypeId: number | null;
  assetTypeName: string | null;
  assetTypeFullPath: string | null;
  manufacturerId: number | null;
  manufacturerName: string | null;
  model: string | null;
  serialNumber: string | null;
  statusId: number;
  statusCode: string;
  statusName: string;
  locationId: number | null;
  locationName: string | null;
  departmentId: number | null;
  ownerUserId: number | null;
  vendorId: number | null;
  poNumber: string | null;
  purchaseDate: string | null;
  purchasePrice: number | null;
  currency: string | null;
  receivedDate: string | null;
  installDate: string | null;
  serviceStartDate: string | null;
  fixedAssetNo: string | null;
  costCenter: string | null;
  notes: string | null;
  warrantyUntil: string | null;
  eolDate: string | null;
  createdAt: string;
  updatedAt: string | null;
  hostname: string | null;
  macAddress: string | null;
  portCount: number | null;
  portSpeed: string | null;
  poeSupport: boolean | null;
  firmwareVersion: string | null;
  firmwareUpdatedAt: string | null;
  stackInfo: string | null;
  uplinkAssetId: number | null;
  uplinkAssetLabel: string | null;
  managementIpAddress: string | null;
}

export interface NetworkDeviceRequest {
  assetTypeId: number;
  name: string;
  manufacturerId: number | null;
  model: string | null;
  serialNumber: string | null;
  statusId: number;
  locationId: number | null;
  departmentId: number | null;
  ownerUserId: number | null;
  vendorId: number | null;
  poNumber: string | null;
  purchaseDate: string | null;
  purchasePrice: number | null;
  currency: string | null;
  receivedDate: string | null;
  installDate: string | null;
  serviceStartDate: string | null;
  fixedAssetNo: string | null;
  costCenter: string | null;
  notes: string | null;
  eolDate: string | null;
  hostname: string | null;
  macAddress: string | null;
  portCount: number | null;
  portSpeed: string | null;
  poeSupport: boolean | null;
  firmwareVersion: string | null;
  firmwareUpdatedAt: string | null;
  stackInfo: string | null;
  uplinkAssetId: number | null;
  managementIpAddress: string | null;
}
